"""change img

Revision ID: 1bda8e747eab
Revises: f5aecfec402b
Create Date: 2024-04-28 11:37:14.848018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bda8e747eab'
down_revision: Union[str, None] = 'f5aecfec402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('img', sa.Text(), server_default='', nullable=True))
    op.alter_column('carpets', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.drop_column('carpets', 'img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('carpets', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.drop_column('carpets', 'img')
    # ### end Alembic commands ###
