"""add vis

Revision ID: 336d5b6c8d9f
Revises: ed1bf6bd0c7a
Create Date: 2024-06-05 13:20:12.288217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336d5b6c8d9f'
down_revision: Union[str, None] = 'ed1bf6bd0c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('visibility_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carpets', 'visibility_status')
    # ### end Alembic commands ###
