"""add data

Revision ID: 8cd2b8bab045
Revises: 71b4c8ae9e85
Create Date: 2024-05-27 15:19:48.260890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd2b8bab045'
down_revision: Union[str, None] = '71b4c8ae9e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpets', sa.Column('form', sa.String(), nullable=True))
    op.add_column('carpets', sa.Column('color', sa.String(), nullable=True))
    op.add_column('carpets', sa.Column('pattern', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('patronymic', sa.String(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('carpets', 'pattern')
    op.drop_column('carpets', 'color')
    op.drop_column('carpets', 'form')
    # ### end Alembic commands ###
