"""add payment_id

Revision ID: ed1bf6bd0c7a
Revises: 8cd2b8bab045
Create Date: 2024-06-04 21:18:08.007256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1bf6bd0c7a'
down_revision: Union[str, None] = '8cd2b8bab045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_id', sa.String(), nullable=True))
    op.drop_column('users', 'ya_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ya_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'payment_id')
    # ### end Alembic commands ###
